name: Build Community Catalog PR branch (test build)

on:
  # Run this workflow on changes to any PR.
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build production (test build)
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: 'lts/hydrogen'
      output: 'dist'
      script: 'build'
