name: Deploy Community Catalog production

on:
    # Run this workflow on push to production-release tag (via chatops)
    push:
        tags:
          - production-release

    # Allow running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    name: Build production
    uses: zooniverse/ci-cd/.github/workflows/npm_build.yaml@main
    with:
      commit_id: ${{ github.sha }}
      node_version: 'lts/iron'
      output: 'dist'
      script: 'build'

  deploy:
    name: Deploy production
    uses: zooniverse/ci-cd/.github/workflows/deploy_static.yaml@main
    needs: build
    with:
      source: 'dist'
      target: 'community-catalog.zooniverse.org'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}

  slack_notification:
    name: Send Slack notification
    uses: zooniverse/ci-cd/.github/workflows/slack_notification.yaml@main
    needs: deploy
    if: always()
    with:
      commit_id: ${{ github.sha }}
      job_name: Build production / build
      status: ${{ needs.deploy.result }}
      title: 'Community Catalog Production deploy complete'
      title_link: 'https://community-catalog.zooniverse.org'
    secrets:
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
