name: Run Community Catalog tests

on:
  # Run this workflow on creation (or sync to source branch) of a new pull request
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - run: npm ci
    - run: npm test
